SELECT
    COUNT(*) AS TOTAL_EMPLOYEES,
    AVG(SALARY) AS AVERAGE_SALARY,
    SUM(SALARY) AS TOTAL_SALARY,
    MIN(SALARY) AS MINIMUM_SALARY,
    MAX(SALARY) AS MAXIMUM_SALARY
FROM Employee_Table;