CREATE TABLE Employee_Table (
    EMP_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALARY DECIMAL(10, 2),
    DEPARTMENT VARCHAR(50),
    DEPT_ID INT,
    RATING INT(1)
);