SELECT EMP_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, SALARY
FROM Employee_Table
WHERE (DEPARTMENT = 'Sales' AND SALARY > 50000)
   OR (DEPARTMENT = 'HR' AND SALARY <> 40000)
ORDER BY DEPARTMENT ASC, SALARY DESC;